---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: production
  name: db-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db-service
    spec:
      initContainers:
      - image: akubrachenko/init-container:test
        name: init-container-postgres
        env:
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: dbname
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        command: ['sh', '-c', 'until pg_isready -h srmsystemdb -p 5432; do echo waiting for database; sleep 2; done;']
      containers:
      - image: akubrachenko/db-service:test
        name: db-service
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_HOST
          value: srmsystemdb
        - name: POSTGRES_PORT
          value: "5432"
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: dbname
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password 
---
kind: Service
apiVersion: v1
metadata:
  namespace: production
  name: db-service
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
